---
language: node_js
node_js:
  - "10"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn --version
  - npm install -g bower
  - bower --version

install:
  - yarn install

jobs:
  fail_fast: true
  include:
    - stage: tests
      name: "Node 10 With Coverage"
      script:
      - yarn lint
      - yarn node-test-with-coverage

    - stage: additional tests
      name: floating dependencies
      install: yarn install --no-lockfile

    - name: "All Commands Smoke Test"
      script:
      - yarn client-test

    - name: "Node 6 Smoke Test"
      node_js: "6"
      script:
      - yarn smoke-test

    - name: "Node 8 Smoke Test"
      node_js: "8"
      script:
      - yarn smoke-test

script:
  - yarn node-test
